
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  {{ if.Values.postgresql.storageClassName }}
  storageClassName: {{ .Values.postgresql.storageClassName }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- end }}

{{- if .Values.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  {{ if.Values.redis.storageClassName }}
  storageClassName: {{ .Values.redis.storageClassName }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- end }}
